---
title: "Corona map"
author: "Jenny Eriksson"
date: '2020-05-18'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
library(leaflet)
library(plotly)
```

```{r, include=FALSE}
if(!file.exists("corona.csv"))
{
download.file("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/05-17-2020.csv", "corona.csv")
}
data<-read.csv("corona.csv")
```
The following map shows the number of reported confirmed cases and deaths per country, up until 2020-05-18. Hover the data to get the number.
```{r, include=FALSE}
library(dplyr)
names(data)[6]<-"lat"
names(data)[7]<-"lng"
deaths<-data %>% group_by(Country_Region) %>% summarize(tot_death=sum(na.omit(Deaths)), tot_cases=sum(na.omit(Confirmed)), lat=na.omit(lat)[which.max(Confirmed)], lng=na.omit(lng)[which.max(Confirmed)], Country=Country_Region[1])
deaths<-deaths[complete.cases(deaths), ]

deaths$hover <- with(deaths, paste(Country, "Deaths: ", tot_death, "Disease: ", tot_cases))


```


```{r, echo=F}

map_options <- list(
    projection = list(type = 'Mercator'),
    showcountries = TRUE
)
plot_geo(deaths, lat=~lat, lon=~lng, color=~tot_death*30) %>% add_markers(text=deaths$hover, size=deaths$tot_death, sep = "<br />") %>%layout(title='Corona map', geo=map_options)

```

```{r, echo=F}
# Plot on pie chart
plot_ly(deaths, type='pie', labels = ~Country, values = ~tot_death, textposition = 'inside') %>%layout(title='Pie chart')
```

```{r, echo=F}
# Plot on bar chart
deaths<-deaths[order(deaths$tot_death, decreasing = T),]
deaths<-deaths[1:20,]

xform <- list(categoryorder = "array",
              categoryarray = deaths$Country)

plot_ly(deaths, type='bar', x = ~Country, y = ~tot_death, hovertemplate=deaths$hover) %>%layout(title='Bar chart', xaxis=xform)
```

